### PR TITLE
Set APPEND_PROJECT_NAME_TO_INCLUDEDIR to ON

### PR DESCRIPTION
**Pull request by sloretz**
https://github.com/eProsima/Fast-DDS/pull/2535
https://github.com/eProsima/Fast-CDR/pull/120
https://github.com/eclipse-cyclonedds/cyclonedds/pull/1169

This is in support of ros2/ros2#1150

Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@sloretz is this a CMake argument which should be added to the packaging jobs as well?

**Comment by sloretz** [comment]
> @sloretz is this a CMake argument which should be added to the bloom patches for packaging as well?

Definitely, though I don't know how to do that. Willing to teach me? I opened an issue here: https://github.com/ros2-gbp/fastcdr-release/issues/9

**Comment by sloretz** [comment]
> @sloretz is this a CMake argument which should be added to the bloom patches for packaging as well?

@nuclearsandwich Would you be willing to review these PRs updating the debian and rpm rules on the release repos for Fast-CDR, Fast-DDS, and Cyclone-DDS?

https://github.com/ros2-gbp/fastcdr-release/pull/10
https://github.com/ros2-gbp/fastcdr-release/pull/11
https://github.com/ros2-gbp/fastrtps-release/pull/21
https://github.com/ros2-gbp/fastrtps-release/pull/22
https://github.com/ros2-gbp/cyclonedds-release/pull/9
https://github.com/ros2-gbp/cyclonedds-release/pull/10

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by sloretz** [comment]
CI (build and test all, but with this CI scripts branch)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16458/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11048/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16810/)

**Comment by sloretz** [comment]
Rebased and Trying CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16459/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11049/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16811/)

**Comment by sloretz** [comment]
CI LGTM

Linux and windows jobs have test failures, however the important thing is all packages built. This change should only affect where headers are found.

The linux test failures appear the same as the last nightly: https://ci.ros2.org/view/nightly/job/nightly_linux_release/2233/#showFailuresLink

The windows failures are known flaky tests in `rosbag2`: https://github.com/ros2/rosbag2/issues/732

**Comment by clalancette** [comment]
> The linux test failures appear the same as the last nightly: https://ci.ros2.org/view/nightly/job/nightly_linux_release/2233/#showFailuresLink

Yes, those should be fixed by https://github.com/ros2/ci/pull/648 (you just happened to run CI before that was merged).

> The windows failures are known flaky tests in `rosbag2`: [ros2/rosbag2#732](https://github.com/ros2/rosbag2/issues/732)

Yes, absolutely.  This looks good to me, I'll add another approval.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
