### PR TITLE
remove OpenSplice from packaging jobs

### PR DESCRIPTION
**Pull request by dirk-thomas**
Follow up of #380.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
It has been publically announced on Doscourse over a month ago. So I don't plan to send any additional announcement for this.

Also there are no navigation2 test jobs for Foxy.

**Comment by dirk-thomas** [comment]
> The osrf/ros2:nightly image is based on the Linux binaries

I created osrf/docker_images#379.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/opensplice-move-to-eclipse-cyclone-dds-in-ros-2/12370/9

**Comment by dirk-thomas** [comment]
Just for the record: the nightly archive didn't contain OpenSplice for a while - since the repository was removed from the ros2.repos file in ros2/ros2#865.

**Pull request merged**
