### PR TITLE
install actionlib

### PR DESCRIPTION
**Pull request by ipa-hsd**
install actionlib dep needed for ros1_bridge

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/jenkins-ci-for-ros1-bridge/26653/5

**Review by clalancette — APPROVED** [review]
This looks reasonable to me.  I'm going to run a couple of different CIs on it just to make sure nothing gets broken.

**Comment by clalancette** [comment]
Rolling regular CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17155/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11700/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17577/)

Foxy regular CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17156/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11701/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17578/)

Foxy packaging CI (to test building the bridge):
* Linux [Build Status](http://ci.ros2.org/job/ci_packaging_linux/521/)

**Comment by clalancette** [comment]
Foxy Windows is unstable, but that's just how it rolls.  This otherwise looks good to me, so I'm going to go ahead and merge it.  Thanks for the PR.

**Pull request merged**
