### PR TITLE
Fixes to get Jammy Python 3.10 CI building

### PR DESCRIPTION
**Pull request by clalancette**
The individual commits have more information about why we need each of the changes.  Still a draft since we need to run CI in a few different places before we can call this ready to go.

* https://github.com/ros2/ci/pull/642
* #636 
* https://github.com/ros2/ci/pull/643
* https://github.com/ros2/ci/pull/644

### CODE REVIEW

**Comment by clalancette** [comment]
* Linux on a host that is forced updated to Jammy Python 3.10 [Build Status](http://ci.ros2.org/job/test_ci_linux/79/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16740/)

**Comment by nuclearsandwich** [comment]
I'm good on keeping things rolled up into one branch during CI builds but I do think that we'll want to split commits into their own PRs or at least plan to rebase-merge rather than squash merge this PR in order to maintain the conversation behind these changes.

**Comment by clalancette** [comment]
Here's some additional builds:

* Foxy on Linux: [Build Status](http://ci.ros2.org/job/test_ci_linux/81/)
* Rolling on RHEL: [Build Status](http://ci.ros2.org/job/ci_linux-rhel/197/)

**Comment by nuclearsandwich** [comment]
This PR ended up a tracking issue for individual PRs with each change reviewed independently and has been superseded by those PRs.

**Pull request closed without merging**
