### PR TITLE
Support packaging job on xenial

### PR DESCRIPTION
**Pull request by dhood**
followup of https://github.com/ros2/ci/pull/188

https://github.com/ros2/ci/pull/178 added support for bionic or xenial on CI jobs; this does the same for packaging jobs.

(test jobs that will get deleted after this is merged)
linux xenial: [Build Status](https://ci.ros2.org/job/test_packaging_xenial_linux/1/)
linux bionic: [Build Status](https://ci.ros2.org/job/test_packaging_xenial_linux/2/)
arm xenial: [Build Status](https://ci.ros2.org/view/All/job/test_packaging_xenial_linux-aarch64/1/)
arm bionic: [Build Status](https://ci.ros2.org/view/All/job/test_packaging_xenial_linux-aarch64/2/)

### CODE REVIEW

**Comment by dhood** [comment]
this needs to be deployed before the nightlies to avoid failing xenial packaging jobs tonight

**Comment by dhood** [comment]
thanks! was a bit confused how it passed yesterday and today but not overnight but that explains it :)

**Comment by dhood** [comment]
nw I'll delete them unless you still want reference to https://ci.ros2.org/view/All/job/test_packaging_xenial_linux/4/?

**Comment by mikaelarguedas** [comment]
No that's fine we can delete them :+1:

**Pull request merged**
