### PR TITLE
install net-tools for ifconfig in docker image

### PR DESCRIPTION
**Pull request by wjwwood**
fixes https://github.com/ros2/build_cop/issues/26

### CODE REVIEW

**Comment by dhood** [comment]
I think it might need CI for ARM given https://github.com/ros2/ci/issues/75

**Comment by mikaelarguedas** [comment]
> I think it might need CI for ARM given #75

Yeah, this is in the middle of a series of very similar commands without any add commande before so it would be very surprising. I'll leave it up to @wjwwood to run CI or not

**Comment by wjwwood** [comment]
I started a job just to make sure if got rid of the ifconfig missing issue:

http://ci.ros2.org/job/ci_linux/2651/console

It looks good, but I'll also run an ARM job as @dhood suggested.

**Comment by dhood** [comment]
Now that I remember what originally caused that issue to appear, I also launched [Build Status](http://ci.ros2.org/job/ci_turtlebot-demo_linux-aarch64/33/) because it was the extra lines that are only in the turtlebot dockerfile that caused it to show up on ARM (https://github.com/ros2/ci/pull/74)

**Comment by wjwwood** [comment]
Thanks @dhood the ARM job passed docker and the issue was fixed:

http://ci.ros2.org/job/ci_linux-aarch64/206/console

I'll wait for the job you launched to get past docker before merging.

**Comment by wjwwood** [comment]
@dhood did it fail in the same way?

**Comment by dhood** [comment]
yes, unfortunately. there's an issue linked to [in this comment](https://github.com/ros2/ci/issues/75#issuecomment-302186809) that might have the permanent fix, but the temporary workaround is to merge lines in the dockerfile (we're hitting some layer limit)

**Comment by wjwwood** [comment]
I'm going to try again with ab4085fb4e20597c62bf82843eb3fc266a45bb6c

**Comment by mikaelarguedas** [comment]
My bad, I thought it was related to the type of command not the number of layers. Thanks @dhood  for checking

**Comment by mikaelarguedas** [comment]
Maybe we should rename https://github.com/ros2/ci/issues/75 accordingly now that we know more about the issue

**Comment by wjwwood** [comment]
http://ci.ros2.org/job/ci_linux-aarch64/207/console is working, so I'll merge this.

**Pull request merged**
