### PR TITLE
Update recipe for qt download path.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Qt has moved the 5.12.10 offline installer that we rely on for Windows.

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
The change looks good to me, but I think we need a PR to ros2-cookbooks, as well, correct?

**Comment by nuclearsandwich** [comment]
https://github.com/ros-infrastructure/ros2-cookbooks/pull/49

**Comment by nuclearsandwich** [comment]
[Build Status](https://ci.ros2.org/job/ci_windows/18003/) is a rebuild of a job which failed previously and is now past the infra part of the build.

**Review by clalancette — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
This PR now includes #680 since the changes here are required for those builds to succeed.

**Pull request merged**
