### PR TITLE
Extend nightly address sanitizer job to run on more green packag…

### PR DESCRIPTION
**Pull request by prajakta-gokhale**
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
@nuclearsandwich could you please take a look?

**Comment by nuclearsandwich** [comment]
[Build Status](https://ci.ros2.org/job/ci_linux/8493/)

**Comment by thomas-moulard** [comment]
@prajakta-gokhale I think you're the last one who touched this - maybe you know?

**Comment by prajakta-gokhale** [comment]
> I compared the topological package list between the current nightly and the job I just kicked off with this PR and it looks like the only new package is rcl_logging_noop but also like rcpputils got dropped. Was that intentional?

That was not intentional. I will update this PR with the correct package list.

**Comment by prajakta-gokhale** [comment]
CI with build and test `--packages-up-to rcpputils`

[Build Status](https://ci.ros2.org/job/ci_linux/8538/)

**Comment by nuclearsandwich** [comment]
This latest commit adds back rcpputils but removes rcl_logging_noop so there are more packages being tested but no additional ones being built.

**Comment by prajakta-gokhale** [comment]
> This latest commit adds back rcpputils but removes rcl_logging_noop so there are more packages being tested but no additional ones being built.

Yes that was the intention - to test more 'green' packages.

**Comment by thomas-moulard** [comment]
@nuclearsandwich can we merge this?

**Comment by thomas-moulard** [comment]
@nuclearsandwich this is ready, can we merge this?

**Comment by nuclearsandwich** [comment]
Deployed.

**Pull request merged**
