### PR TITLE
Reinstate interface packages

### PR DESCRIPTION
**Pull request by gbiggs**
This PR removes the interface packages from the automatically-ignored list of packages.

Acceptance of this PR should be based on the impact on CI timing.

### CODE REVIEW

**Comment by gbiggs** [comment]
CI without the re-instated packages:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/16253/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10874/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16612/)

**Comment by gbiggs** [comment]
CI with the re-instated packages:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/16254/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10875/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16613/)

**Review by clalancette — APPROVED** [review]
Just looking at the history of this stuff, these blacklists were added like 5 years ago.  I think it is about time to take them out.  Looks good to me, CI is green, so I'm going to go ahead and merge this.  Thanks @gbiggs !

**Comment by clalancette** [comment]
> Just looking at the history of this stuff, these blacklists were added like 5 years ago. I think it is about time to take them out. Looks good to me, CI is green, so I'm going to go ahead and merge this. Thanks @gbiggs !

Oh, actually, I forgot to look at the times.  It does seem to have increased the amount of time pretty significantly.  I'm not quite sure why that is, but it bears looking into before we merge.

**Comment by gbiggs** [comment]
For some reason I totally missed any notifications I got about this.

**Comment by gbiggs** [comment]
I wonder if it's possible to re-open a PR...

**Pull request merged**
