### PR TITLE
Pin EmPy to version 3.3.4 on Windows.

### PR DESCRIPTION
**Pull request by clalancette**
This should fix failing builds on e.g. Humble.

This requires https://github.com/ros-infrastructure/ros2-cookbooks/pull/78

A draft until I run further CI on it.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Rolling Windows [Build Status](http://ci.ros2.org/job/ci_windows/23016/)
* Jazzy Windows [Build Status](http://ci.ros2.org/job/ci_windows/23017/)
* Humble Windows [Build Status](http://ci.ros2.org/job/ci_windows/23018/)

**Review by nuclearsandwich — APPROVED** [review]
Once the upstream PR is merged this will need one more bump before merging. But shouldn't need another review.

**Comment by clalancette** [comment]
New CI with the latest:
* Rolling Windows [Build Status](http://ci.ros2.org/job/ci_windows/23050/)
* Jazzy Windows [Build Status](http://ci.ros2.org/job/ci_windows/23051/)
* Humble Windows [Build Status](http://ci.ros2.org/job/ci_windows/23052/)

**Comment by clalancette** [comment]
I've now merged in https://github.com/ros-infrastructure/ros2-cookbooks/pull/78 , and updated the hash here to the latest.  So going ahead and merging this one.

**Pull request merged**
