### PR TITLE
Switch RHEL job from RHEL 7 to 8

### PR DESCRIPTION
**Pull request by cottsay**
Now that we're building RPMs for RHEL 8, we should perform CI using RHEL 8 as well.

This is still using CentOS, so we'll need to find another solution before then end of the year.

Note that there are new test failures and build warnings that will need to be addressed at some point. Having a job to verify those fixes will make that easier, so I don't think we should wait until the build is clean to merge this.

[Build Status](https://ci.ros2.org/job/ci_linux-rhel/115/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems reasonable to me once CI comes back.  I agree that we shouldn't wait for the job to be green to move ahead here, but we should at least make sure it is not red.

**Comment by cottsay** [comment]
Something is messed up with pytest. Sometimes it's using the system's 3.4.2, and sometimes it's using the pip-downloaded version. I'm not sure why, but it seems that something is clobbering the virtualenv or something.

**Comment by cottsay** [comment]
I bumped the system's `pytest` version using pip, and the build is passing now. There is something wrong with the virtualenv - it's not being used by 100% of the tests.

This should be stable for now, but we might want to find time to get to the bottom of that. I'm not sure if it is a RHEL 8 problem, a RHEL problem, or is actually a problem for our other platforms as well, just to a lesser degree.

**Comment by clalancette** [comment]
@cottsay Should we redeploy to the buildfarm here?  I noticed that some of the changes here are not currently reflected on https://ci.ros2.org.

**Comment by cottsay** [comment]
> Should we redeploy to the buildfarm here?

You're right, the changes to the build and test args didn't get deployed. The Dockerfile changes don't require deployment, though.

I'll deploy these changes along with #559.

**Pull request merged**
