### PR TITLE
Update ros2-cookbooks repo for openssl update

### PR DESCRIPTION
**Pull request by brawner**
Not sure why this doesn't update the submodule correctly. Trying out in ci to see what's going on

Edit: Now fixed
Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
[Build Status](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1776/)

**Review by nuclearsandwich — APPROVED** [review]
If the test build comes back successful then we can update the branch and cookbook commit again when the upstream PR merges, then merge this after without a second review.

**Comment by brawner** [comment]
Merged upstream and retesting 
[Build Status](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1778/)

**Comment by nuclearsandwich** [comment]
Thanks for catching and fixing this one!

**Pull request merged**
