### PR TITLE
Unpin cppcheck 1.90

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Reverts ros2/ci#472

Related to https://github.com/ros2/ros2/issues/942

### CODE REVIEW

**Comment by claireyywang** [comment]
Update: I still need to add macro dependency for a bunch of repos reported failure in cppcheck in the original issue.  https://github.com/ros2/rclpy/pull/577 proves adding additional dependency solves the immediate problem, but will require a more general solution later on to improve performance.

**Comment by claireyywang** [comment]
PRs opened and in review
https://github.com/ros2/rosidl/pull/505
https://github.com/ros2/rosidl_typesupport/pull/78
https://github.com/ros2/rosidl_typesupport_fastrtps/pull/49
https://github.com/ros2/rosidl_typesupport_connext/pull/57

Should be good to test out this PR once they are merged

**Comment by ivanpauno** [comment]
@claireyywang friendly ping.
are the linked PRs ready for review?

**Comment by claireyywang** [comment]
@ivanpauno yup!

**Comment by ivanpauno** [comment]
I've approved them all.
They need fresher CI and a double check of those windows/macOS failures (if they are still happening).

If your PRs aren't getting a review, please pick a random reviewer or ask for one in a waffle meeting.
Thanks!

**Comment by claireyywang** [comment]
@nuclearsandwich Im trying to run CIs against this branch but both OSX https://ci.ros2.org/job/ci_osx/9902/console and Windows https://ci.ros2.org/job/ci_windows/12058/console are failing. It seems to have something to do with the rolling release. Can you please update this branch and resolve the conflicts?

**Comment by nuclearsandwich** [comment]
macOS [Build Status](https://ci.ros2.org/job/ci_osx/10407/)
Windows [Build Status](https://ci.ros2.org/job/ci_windows/12636/)

**Comment by nuclearsandwich** [comment]
@claireyywang it looks like your rosidl_typesupport_fastrtps branch has conflicts that need attention. You should be able to re-trigger the two builds above to retry.

**Comment by clalancette** [comment]
At this point, I think we've determined that cppcheck > 1.9 isn't really salvageable.  So we've actually disabled it in ament_lint instead.  With that in mind, I'm going to close this out as I don't think there is a path forward here.  Feel free to reopen if you disagree.

**Pull request closed without merging**
