### PR TITLE
Only install ros1 dependencies when there is a valid ROS 1 distro.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
When on Ubuntu Jammy there is no official ROS 1 distribution available.

Before merging this I want to run it and see how the ros1_bridge builds (hopefully it does just trivially) but it may not in which case more changes will need to be added to better support disabling the bridge.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Ubuntu [Build Status](https://ci.ros2.org/job/ci_packaging_linux/478/)
Ubuntu ARM64 [Build Status](https://ci.ros2.org/job/ci_packaging_linux-aarch64/86/)

**Comment by nuclearsandwich** [comment]
Merging pre-review in order to try and get CI in an improved state.

**Comment by clalancette** [comment]
Looks like an improvement to me, so :+1: .

**Review by Blast545 — COMMENTED** [review]
LGTM

**Pull request merged**
