### PR TITLE
Opensplice version update

### PR DESCRIPTION
**Pull request by rohitsalem**
Updated the linux dockerfile  with latest version of opensplice deb

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch looks good to me. Can you please link to a job which uses this branch.

**Comment by rohitsalem** [comment]
Here : [Build Status](https://ci.ros2.org/job/ci_linux/4196/)

**Comment by mikaelarguedas** [comment]
From the job: `Get:1 http://packages.osrfoundation.org/gazebo/ubuntu xenial/main amd64 libopensplice67 amd64 6.7.180404+osrf1-1~xenial [3,278 kB]`

I'm assuming that the test failures are due to your changes and not the new binary. Is that correct ?
Do you happen to have a job with the new binary and without your changes to confirm it ?

**Comment by rohitsalem** [comment]
Yes, the test failures are due to my changes, No, I ran only a single job with this new binary, I will start a new job with the new binary, with master and let you know.

**Comment by rohitsalem** [comment]
New job [Build Status](https://ci.ros2.org/job/ci_linux/4199/)

**Pull request merged**
