### PR TITLE
Update the Windows ros2-cookbook to the latest.

### PR DESCRIPTION
**Pull request by clalancette**
This is to get the pinned PyQt5 version; see
https://github.com/ros-infrastructure/ros2-cookbooks/pull/13
for more information.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Review by brawner — APPROVED** [review]
Looks good. Should CI be run once more for this PR just to confirm?

**Comment by clalancette** [comment]
> Looks good. Should CI be run once more for this PR just to confirm?

Yeah, definitely.  I'll go ahead and do that.

**Comment by clalancette** [comment]
CI:
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12273/)

**Comment by clalancette** [comment]
This succeeded CI before the current CI problems.  Given that this should fix one of the CI problems, I'm going to go ahead and merge.

**Pull request merged**
