### PR TITLE
Add missing system packages for vendor packages

### PR DESCRIPTION
**Pull request by cottsay**
This is desirable because:
1. It aligns with what the debs will do, which is what most of our users will experience
2. It's faster - less to build
3. It's less error prone - less to download during each build
4. We can easily revert to previous behavior with FORCE_BUILD_VENDOR_PKG

Jammy (Rolling): [Build Status](https://ci.ros2.org/job/ci_linux/18013/)
Focal (Foxy): [Build Status](https://ci.ros2.org/job/ci_linux/18014/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Yes please!  With green CI.

**Comment by cottsay** [comment]
@nuclearsandwich, I'm adding ignition packages here. Do you see any issues with that?

**Review by nuclearsandwich — APPROVED** [review]
Nice catch!

**Review by clalancette — APPROVED** [review]
Looks good with green CI for both Focal and Jammy.

**Pull request merged**
