### PR TITLE
add qt_gui_core dependency

### PR DESCRIPTION
**Pull request by dirk-thomas**
`libboost-filesystem-dev`

Follow up of #216.

### CODE REVIEW

**Comment by wjwwood** [comment]
Why is it necessary? The referenced pr has basically no information in it.

**Comment by dirk-thomas** [comment]
The title mentions that this is a dependency for `qt_gui_core` which happens to use `boost::filesystem`.

**Comment by wjwwood** [comment]
But why not use std::filesytem (like with the `pluginlib/filesystem_helper.hpp` header)? There are no details as to why the decision to not refactor to remove the dependency was made.

**Comment by dirk-thomas** [comment]
@brawner I will let you answer - I only wanted to provide the dependency here...

**Comment by wjwwood** [comment]
I mean, I'm fine with getting the dependency if we can't get rid of it now (though it would be better if we did), but there's no memoranda about this (if I look back on this a year from now, I can't answer "why?").

**Comment by brawner** [comment]
Frankly, because I didn't realize filesystem_helper.hpp existed, so that may fit the task just fine. The code in qt_gui_cpp::RosPluginlibPluginProvider requires finding the parent path and if it's reliable enough in pluginlib::filesystem_helper then I can use that. 

I did not want to rely on <filesystem> or even <experimental/filesystem> because <filesystem> is not installed by default on ubuntu, and <experimental/filesystem> is not in xcode. The current version of VS seems to be unable to compile ros2 currently, so I can only assume that Windows would also have similarly difficulty.

Eventually, it seems like std::filesystem will be included as the bleeding edge compilers are starting to support it. However if you all would prefer to use filesystem_helper rather than boost::filesystem, I can test it out.

**Comment by dirk-thomas** [comment]
The dependency has been removed in https://github.com/ros-visualization/qt_gui_core/commit/b8e44dda7e205522c5fd655afb7d3c5963823de0

Therefore this isn't necessary anymore.

**Pull request closed without merging**
