### PR TITLE
end --only-packages with --

### PR DESCRIPTION
**Pull request by dirk-thomas**
Follow up of ament/ament_tools#114.

### CODE REVIEW

**Comment by dhood** [comment]
I think it's better to move the sourcespace to the front of the argument list since the `--` delimiter will not work if any other optionals are added.

**Comment by dhood** [comment]
since this has been merged we'll just have to keep this in mind in the future.

**Comment by dirk-thomas** [comment]
I don't think a trailing `--` makes the command fail. Some of my local bash aliases always do that and work fine.

**Comment by dhood** [comment]
If we want to package in isolation, [with how it's currently setup in line 53](https://github.com/ros2/ci/blob/4265d10e8dc79f9ba8068baa5fbf045a2611da08/ros2_batch_job/packaging.py#L53), I expect the job to fail:

```
$ ./src/ament/ament_tools/scripts/ament.py build --only-packages ament_tools -- ./src --isolated
usage: ament.py [-h]
                [build | build_pkg | list_packages | package_name | package_version | test | test_pkg | test_results | uninstall | uninstall_pkg]
                ...
ament.py: error: unrecognized arguments: --isolated
```

that's why I recommend moving the positional arguments to the front e.g. 
```
$ ./src/ament/ament_tools/scripts/ament.py build ./src --only-packages ament_tools --isolated
```

**Comment by dirk-thomas** [comment]
Sounds good to me: #11

**Pull request merged**
