### PR TITLE
Remove all references to 'windows-metal'.

### PR DESCRIPTION
**Pull request by clalancette**
It is no longer a build type we have available.

This is kind of a side issue to the main issue of deprecating Foxy, but I figured we should do it while we are here.

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]
Thanks for this cleanup!

**Comment by clalancette** [comment]
As with other PRs, I'm going to deploy this to the `test_` jobs and run CI there.  Once that is happy, I'll merge and fully deploy.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/test_ci_linux/149/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/test_ci_linux-aarch64/61/)
* Windows [Build Status](http://ci.ros2.org/job/test_ci_windows/321/)

**Comment by clalancette** [comment]
All right, merging and deploying.

**Pull request merged**
