### PR TITLE
Install python3-jsonschema as Linux build requirement

### PR DESCRIPTION
**Pull request by emersonknapp**
Requirement from https://github.com/ros2/rosidl/pull/722

See https://github.com/ros2/rosidl/pull/722#discussion_r1120569055

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]
We'll need an additional PR for ROS 2 CI once the cookbook is updated. But this is good for Linux support.

We do need to double check that this package is available in RHEL 9, which we're getting ready to move to for Rolling and Iron.

**Comment by clalancette** [comment]
> We do need to double check that this package is available in RHEL 9, which we're getting ready to move to for Rolling and Iron.

It seems to be available in the default `appstream` repositories for AlmaLinux 9, at least.  @cottsay will that translate to being available in RHEL-9 as well?

**Review by cottsay — APPROVED** [review]
> will that translate to being available in RHEL-9 as well?

It is provided by AppStream in both RHEL 8 and RHEL 9, so this looks good.

**Comment by clalancette** [comment]
Given the latest comments, I'm going to run a quick CI for this on both Ubuntu and RHEL, then merge.

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18171/)
* RHEL 8 [Build Status](http://ci.ros2.org/job/ci_linux-rhel/338/)
* RHEL 9 [Build Status](http://ci.ros2.org/job/ci_linux-rhel/339/)

**Pull request merged**
