### PR TITLE
Add ros1 path to tb job

### PR DESCRIPTION
**Pull request by gerkey**
[This PR contains the changes from #57. That PR should be merged first.]

To build the TB demo, we need to source the ROS 1 setup file so that we can access packages like `kobuki_driver`. This PR sets the `--ros1-path` to `/opt/ros/kinetic`, which causes the `ament build` step to be prefixed with `. "/opt/ros/kinetic/setup.sh" &&`. This should in turn allow us to find ROS 1 packages.

Diff from committing this change to the farm:
~~~
Updating job 'ci_turtlebot-demo'
    <<<
    --- remote config
    +++ new config
    @@ -237,0 +238 @@
    +export CI_ARGS="$CI_ARGS --ros1-path /opt/ros/kinetic"
    >>>
~~~

First job with this change applied:

http://ci.ros2.org/job/ci_turtlebot-demo/15/

### CODE REVIEW

**Comment by wjwwood** [comment]
Looks like this is based on an old version of master (there are conflicts in the `Dockerfile`).

**Comment by gerkey** [comment]
Yeah, I inherited a conflict from #57. That'll go away after @nuclearsandwich resolves and merges that PR. In the meantime, my only change here is to add 3 lines:

https://github.com/ros2/ci/blob/2326dbba195927f313f8764c52e7ee75cb6bf4f5/job_templates/ci_job.xml.em#L170-L172

**Comment by gerkey** [comment]
New CI, with added dependency (ros2/turtlebot2_demo#14):

http://ci.ros2.org/job/ci_turtlebot-demo/16

**Comment by gerkey** [comment]
New CI, trying to keep up with the shifting ground beneath me:

http://ci.ros2.org/job/ci_turtlebot-demo/17/

**Comment by gerkey** [comment]
Again, actually specifying the different repos URL: http://ci.ros2.org/job/ci_turtlebot-demo/18/

**Comment by nuclearsandwich** [comment]
I've updated #57. When it merges, the most expedient way to rebase this PR is probably to just cherry pick 2326dbb onto master.

**Comment by nuclearsandwich** [comment]
@gerkey FYI this has been undeployed while I updated and tested #57. I am running some sanity check builds to make sure that the changes are good and then this can be rebased and redeployed.

**Comment by gerkey** [comment]
I'm too clumsy to cherry-pick the change, so I opened a new PR: #63.

**Pull request closed without merging**
