### PR TITLE
add pytest and pytest-cov to apt packages to install

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Follow-up of https://github.com/ros2/ci/pull/109

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I don't think this achieves what your are describing in the referenced ticket. It installs the Debian packages of `pytest` but later it still installs the packages from `pip` so the environment will still *not* match what a users has when installing only the Debian packages.

**Comment by mikaelarguedas** [comment]
> I don't think this achieves what your are describing in the referenced ticket. It installs the Debian packages of pytest but later it still installs the packages from pip so the environment will still not match what a users has when installing only the Debian packages.

yes but if I build this container I have the same setup as the one of a user following the installation instructions. And these are also the instructions I'll follow on my native machine.

I agree a better outcome would be to not install the pip packages we can get from apt when we run Linux jobs but that's not what I was aiming in my original comment.

**Comment by dirk-thomas** [comment]
With 7f057ebbe94a8b17ef3b9ba2fee28a967295192a the patch reflect the instructions as well as what we actually need.

**Comment by mikaelarguedas** [comment]
Ok merging as is as this matches what is in the instructions

**Pull request merged**
