### PR TITLE
Add in a constraints file for flake8.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
Rolling CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17076/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11629/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17495/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/17496/)
* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/253/)

Foxy CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17077/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11630/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17498/)

**Comment by clalancette** [comment]
This is an alternative to #675 , that just adds in a constraint to flake8, rather than trying to pin it.  This should be the minimum we need to keep flake8 to an earlier version for now.

**Review by Blast545 — APPROVED** [review]
LGTM with green CI.
Context for extra reviewers: https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-c.

**Review by cottsay — APPROVED** [review]

**Comment by wjwwood** [comment]
In the future, please print out files like the `constraint.txt`, it makes it kind of impossible to know what was used in a build. This file isn't reflected in the output of `pip` either, so without looking at this code it's hard to know what was in that file (especially if it changes over time).

Also, it's out of sync with our Windows source instructions:

http://docs.ros.org/en/rolling/Installation/Alternatives/Windows-Development-Setup.html#install-python-prerequisites

> [Install Python prerequisites](http://docs.ros.org/en/rolling/Installation/Alternatives/Windows-Development-Setup.html#id15)
> 
> Install additional Python dependencies:
> 
> `pip install -U colcon-common-extensions coverage flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes mock mypy==0.931 pep8 pydocstyle pytest pytest-mock vcstool`

**Comment by wjwwood** [comment]
I was going to open a pr to print out the file, but @clalancette do you remember if there was a reason for the file versus the inline constraints? Maybe it's not possible to do the `<5.0.0` outside of the file?

**Comment by clalancette** [comment]
> I was going to open a pr to print out the file, but @clalancette do you remember if there was a reason for the file versus the inline constraints? Maybe it's not possible to do the `<5.0.0` outside of the file?

I don't remember.  I didn't actually know that you could do constraints on the command-line.  I think a PR to print out the contents of `constraints.txt` would be fine.

**Pull request merged**
