### PR TITLE
Add osx mojave CI jobs

### PR DESCRIPTION
**Pull request by j-rivero**
As part of the work to support officialy Mojave I have created a new node in that system and connected it to the ros2 buildfarm: https://ci.ros2.org/computer/mac_mojave_lore/. In the new node I used the Jenkins web GUI to inject the enviroment variables: `ROS_DOMAIN_ID`, `OSPL_HOME` and `PATH`. This probably needs to be reverted by the usual method in the rest of the nodes.

This PR tries to implement the code to generate CI jobs that will run daily on that system to check everything is fine there. I think that @nuclearsandwich used these changes to create the job: https://ci.ros2.org/job/test_ci_osx_mojave/

I'm currently hunting the runtime errors present in that job.

### CODE REVIEW

**Comment by j-rivero** [comment]
Problems I found in the testing CI:

1.[ problems loading](https://ci.ros2.org/view/All/job/test_ci_osx_mojave/3/consoleFull) _rclpy.cpython-37m-darwin.so . 
```
19:08:43 11: E   ImportError: dlopen(/Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/install/rclpy/lib/python3.7/site-packages/rclpy/_rclpy.cpython-37m-darwin.so, 2): Library not loaded: @rpath/librclpy_common.dylib
19:08:43 11: E     Referenced from: /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/install/rclpy/lib/python3.7/site-packages/rclpy/_rclpy.cpython-37m-darwin.so
19:08:43 11: E     Reason: image not found
19:08:43 11: E   The C extension '/Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/install/rclpy/lib/python3.7/site-packages/rclpy/_rclpy.cpython-37m-darwin.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
19:08:43 11: - generated xml file: /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/build/message_filters/test_results/message_filters/directed.py.xunit.xml -
```
If I run the same command locally using ssh into the box or even using Jenkins interface to run it, it finished without errors:

https://ci.ros2.org/job/_lore_playground/2/console

```
lore:~ jenkins$ . /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/install/setup.bash
lore:~ jenkins$  /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/venv/bin/python3 -u -m pytest /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/src/ros2/message_filters/test/directed.py -o cache_dir=/Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/build/message_filters/ament_cmake_pytest/directed.py/.cache --junit-xml=/Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/build/message_filters/test_results/message_filters/directed.py.xunit.xml --junit-prefix=message_filters
=============================================================================================== test session starts ================================================================================================
platform darwin -- Python 3.7.4, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
cachedir: /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/build/message_filters/ament_cmake_pytest/directed.py/.cache
rootdir: /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/src/ros2/message_filters
plugins: repeat-0.8.0, cov-2.7.1, rerunfailures-7.0
collected 1 item                                                                                                                                                                                                   

../osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/src/ros2/message_filters/test/directed.py .                                                                                                            [100%]

------------------------------ generated xml file: /Users/osrf/jenkins-agent/workspace/test_ci_osx_mojave/ws/build/message_filters/test_results/message_filters/directed.py.xunit.xml ------------------------------
============================================================================================= 1 passed in 0.23 seconds =============================================================================================
```

**Comment by wjwwood** [comment]
> If I run the same command locally using ssh into the box or even using Jenkins interface to run it, it finished without errors:

My initial guess is that the `DYLD_LIBRARY_PATH` is getting stripped somewhere due to SIP.

**Comment by j-rivero** [comment]
> My initial guess is that the `DYLD_LIBRARY_PATH` is getting stripped somewhere due to SIP.

Thanks for the tip William. The first complete build appeared after removing the SIP protection:
https://ci.ros2.org/job/test_ci_osx_mojave/ (20 failing tests)

**Comment by j-rivero** [comment]
Some notes from my experience installing the lore node:

 * pyqt from brew was missing from existing installation instructions
 * `xcode-select` needs a full installation (use app store, it is not enough to have the command line client)  in order to compile Ogre correctly.
 * I had problems setting up variables (`OSPL_HOME`, `PATH` or `ROS_DOMAIN_ID`) in .bashrc or .bash_profile for Jenkins. I ended up using the Node configure to inject these variables into the build.
 * pydot was missing. I used pip3 to install it.

I used different documents and materials for guiding me through the process of provisioning the node, not sure where to put this additions. @nuclearsandwich any recommendation?

**Comment by wjwwood** [comment]
> `xcode-select` needs a full installation (use app store, it is not enough to have the command line client) in order to compile Ogre correctly.

Can you expand on this, I installed xcode from the app store and it still doesn't let me compile ogre.

**Comment by wjwwood** [comment]
I get errors like this in the `rviz_ogre_vendor` package:

```
[  0%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/OgreASTCCodec.cpp.o
In file included from /Users/william/ros2_ws/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreASTCCodec.cpp:29:
In file included from /Users/william/ros2_ws/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreStableHeaders.h:40:
In file included from /Users/william/ros2_ws/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include/OgrePrerequisites.h:30:
/Users/william/ros2_ws/build/rviz_ogre_vendor/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include/OgrePlatform.h:150:13: fatal error: 'Availability.h' file not found
#   include "Availability.h"
            ^~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by wjwwood** [comment]
I was able to get past the issue building Ogre by running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` (at @j-rivero's suggestion). Basically since I had command-line tools before installing xcode I needed to manually switch.

This absolutely needs to be part of the installation, since until now we've recommended people install the command-line tools only rather than having to get xcode from the app store.

It would be nice to fix Ogre to not need xcode itself, which is probably possible, but I doubt anyone will have time to figure that out by eloquent.

**Comment by wjwwood** [comment]
Now I'm just stuck on this issue: https://github.com/ros2/rviz/issues/440

@Karsten1987 seems to work around this by disabling building of tests, which isn't an ideal workaround.

**Comment by nuclearsandwich** [comment]
This PR was set up to provide specialized Mojave builds in a heterogeneous environment with Sierra and Mojave macs. With Sierra support now over, we have actually transitioned all hosts to Mojave natively. And no longer need Mojave-specific jobs.

The test deployments of this PR are what allowed us to get to this point. So I raise a glass and tip my hat to @j-rivero and company.

**Pull request closed without merging**
