### PR TITLE
Remove bare metal windows configs and set containers as default

### PR DESCRIPTION
**Pull request by brawner**
This PR sets windows-containers as the only windows configuration. Unless they are deleted from the ci.ros2.org, the win jobs will remain because this PR renames all windows jobs to use 'windows' in their job names.

This will need to be checked before being committed to ci.ros2.org.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
If we decide to remove all the name shortening logic we should also manually rename the existing jobs to keep their history.

**Comment by dirk-thomas** [comment]
I though the idea was to *not* change the naming and break all existing links?

**Comment by nuclearsandwich** [comment]
> I though the idea was to _not_ change the naming and break all existing links?

Right. This. I knew there was a reason renaming wouldn't be sufficient.

**Comment by brawner** [comment]
Ok, so we need to leave ci_windows as is then? Same thing with the packaging jobs?

**Comment by brawner** [comment]
Ok this has been updated. Everything referencing the 'windows' os-config is now 'windows-metal', and 'windows-container' is the new windows.

I've also disabled nightly and packaging jobs for windows-metal.

**Comment by nuclearsandwich** [comment]
This is deployed and the `-container` job variants have been disabled.

**Pull request merged**
