### PR TITLE
Revert temporary hack to keep logs on Windows

### PR DESCRIPTION
**Pull request by dirk-thomas**
Reverts #242 once the necessary debug information was extracted.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@cottsay I unassigned myself from the ticket since this item is blocked on the problem to happen on the buildfarm again and the build cop to extract the necessary logs. We could assign the current build cop instead?

**Comment by sloretz** [comment]
@dirk-thomas I collected what I could in ros2/build_cop#161, but CI needed windows nodes so I killed the stuck processes and let it run. If that ticket has enough info to debug the issue then I think this can be merged.

**Comment by dirk-thomas** [comment]
> If that ticket has enough info to debug the issue then I think this can be merged.

It will take some time to review the new logs and determine if the information help to come up with a patch. Therefore I would suggest to wait with merging this.

**Comment by dirk-thomas** [comment]
Since we were able to identify the problem and the necessary fix is described in https://github.com/ros2/build_cop/issues/161#issuecomment-463760815 I will go ahead and merge this revert.

**Pull request merged**
