### PR TITLE
Pin setuptools version to 60.0.4

### PR DESCRIPTION
**Pull request by Blast545**
packaging_linux-aarch64 job failed: https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1868/ with error: 

<details>

```
02:31:08 ==> "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/bin/python" -m pip freeze --all
02:31:08 Fatal Python error: init_import_size: Failed to import the site module
02:31:08 Python runtime state: initialized
02:31:08 Traceback (most recent call last):
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 769, in <module>
02:31:08     main()
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 749, in main
02:31:08     paths_in_sys = virtual_addsitepackages(paths_in_sys)
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 645, in virtual_addsitepackages
02:31:08     return addsitepackages(known_paths, sys_prefix=sys.real_prefix)
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 279, in addsitepackages
02:31:08     addsitedir(sitedir, known_paths)
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 202, in addsitedir
02:31:08     addpackage(sitedir, name, known_paths)
02:31:08   File "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/lib/python3.8/site.py", line 170, in addpackage
02:31:08     exec(line)
02:31:08   File "<string>", line 1, in <module>
02:31:08 AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'
02:31:08 <== '. venv/bin/activate && "/home/jenkins-agent/workspace/packaging_linux-aarch64/venv/bin/python" -m pip freeze --all' exited with return code '1'
02:31:08 Build step 'Execute shell' marked build as failure
```
</details>
Related to: https://github.com/pypa/setuptools/issues/2957, that's supposedly fixed

This PR attempts to fix it. The error is happening before the setuptools installation, in the ccache step, so I'm wondering if it would require an extra step to fix.

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
ci_packaging_aarch64#81
[Build Status](https://ci.ros2.org/job/ci_packaging_linux-aarch64/81/)

**Comment by clalancette** [comment]
You may also have to pin it in the [Dockerfile](https://github.com/ros2/ci/blob/59a1575a52fa7a230dbe93a1e4e90beea427b90b/linux_docker_resources/Dockerfile#L70).

**Comment by Blast545** [comment]
@clalancette You are right, thanks! added with b3cd3b4

**Comment by Blast545** [comment]
I triggered one reference job without the PR to see if we see the same error in the ci_packaging version, and it's not there.

[Build Status](https://ci.ros2.org/job/ci_packaging_linux-aarch64/82/)

**Comment by Blast545** [comment]
@clalancette FYI, ci_packaging passed today, version available was bumped from 60.1 to 60.2
https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1869/

The original issue is fixed starting from this newer version.

**Comment by clalancette** [comment]
Ah, good to know.  So can we just close this PR then?

**Pull request closed without merging**
