### PR TITLE
install lark-parser

### PR DESCRIPTION
**Pull request by dirk-thomas**
Install the Python package `lark-parser` to parse IDL files.

### CODE REVIEW

**Comment by jacobperron** [comment]
> 1. Should we install the branch via pip install git+https://.../lark.git@earley_sppf and create a Debian package of that state for the Linux releases?
> 2. Or should be create a vendor package instead (likely a fork of the upstream repo/branch with a package.xml file added)?

:thinking: Whichever is less work? In any case I presume we'll want to switch to a future version upstream when possible.

**Comment by dirk-thomas** [comment]
Option 1. is certainly what we want long term. Creating the Debian package is some effort but once there is a real release out with the state we need we can even push that one into Debian if we want to.

**Comment by jacobperron** [comment]
I haven't looked too closely at commits, but would it make more sense to use a more recent branch like `0.7` or `0.7b`? Then we'll hopefully closer match the next release version when it's ready. `earley_sppf` is 68 commits behind.

**Comment by dirk-thomas** [comment]
Both of the branches do work for us (`0.7`, `0.7b`). Not sure which one we want to choose - they have different commit(s) on them.

**Comment by dirk-thomas** [comment]
I updated the patch to use the branch `0.7b` recommended by upstream.

**Pull request merged**
