### PR TITLE
Support Connext in packaging jobs, package all rmw impls by default

### PR DESCRIPTION
**Pull request by dhood**
Not tested yet because the farm is busy

### CODE REVIEW

**Comment by dhood** [comment]
[OSX packaging job](https://ci.ros2.org/job/test_packaging_osx/1/) with all 3 RMW implementations works. Doesn't really need https://github.com/ros2/rmw_connext/pull/274 because osx is usually installed in the same location (/Applications). Provided it's the same connext version, it just works. It requires opensplice to be found still if the archive was built with it.

**Comment by dhood** [comment]
OSX: as previously mentioned, works fine provided all rmw implementations from underlay (with static typesupport) are also available at runtime (i.e. even if you're not trying to use connext you need it installed). **Happy to configure OS X packaging job to have different default combo if we prefer** (e.g. because we don't want users to have to have all 3 installed to use our artifacts).

Linux: can have any combination of rmw impls installed at runtime. If you request one that's not setup: `[ERROR] [rcl]: Error getting RMW implementation identifier / RMW implementation not installed (expected identifier of 'rmw_connext_cpp'), exiting with 1.` (can still build overlay). If you install it, you can use it. Works fine with connext from debs in underlay and connext from the website, and with connext from website in underlay, when used with https://github.com/ros2/rmw_connext/pull/274

Windows: presumably same as linux because in the past the only difference has been on osx (https://github.com/ros2/ros2/issues/437)

You have to have exactly the same connext version (5.3.0 won't work, must be 5.3.1). For the record, on my laptop running os x 10.10, the connext binaries designed for sierra work fine.

**Comment by dirk-thomas** [comment]
What are the exact errors when not having e.g. Connext installed and:
* Trying to run the demo talker node
* Building a package in an overlay

**Comment by dhood** [comment]
Speaking about OS X only here:

Overlays can be built fine, but `talker` for example, even in the overlay, is still linked against connext and opensplice typesupport.

Without opensplice:

```
$ ros2 run demo_nodes_cpp listener
Failed to load entry point 'echo': dlopen(/Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libcmxml.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/librcl_interfaces__rosidl_typesupport_opensplice_c.dylib
  Reason: image not found
The C extension '/Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so' failed to be imported while being present on the system. Please refer to 'https://github.com/ros2/ros2/wiki/Rclpy-Import-error-hint' for possible solutions
dyld: Library not loaded: @rpath/libcmxml.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/libexample_interfaces__rosidl_typesupport_opensplice_c.dylib
  Reason: image not found

$ ./lib/demo_nodes_cpp/talker
dyld: Library not loaded: @rpath/libcmxml.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/libexample_interfaces__rosidl_typesupport_opensplice_c.dylib
  Reason: image not found
Trace/BPT trap: 5
```

Without connext:
```
$ ros2 run demo_nodes_cpp talker
Failed to load entry point 'echo': dlopen(/Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/libnddsc.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/librcl_interfaces__rosidl_typesupport_connext_c.dylib
  Reason: image not found
The C extension '/Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so' failed to be imported while being present on the system. Please refer to 'https://github.com/ros2/ros2/wiki/Rclpy-Import-error-hint' for possible solutions
dyld: Library not loaded: @loader_path/libnddsc.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/libexample_interfaces__rosidl_typesupport_connext_c.dylib
  Reason: image not found

$ ./lib/demo_nodes_cpp/talker
dyld: Library not loaded: @loader_path/libnddsc.dylib
  Referenced from: /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/libexample_interfaces__rosidl_typesupport_connext_c.dylib
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by dirk-thomas** [comment]
> Speaking about OS X only here:

What does `ldd _rclpy.cpython-36m-darwin.so` output?

**Comment by dhood** [comment]
```
$ otool -L /Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so
/Users/dhood/Downloads/ros2-osx-connext_packaging/lib/python3.6/site-packages/rclpy/_rclpy.cpython-36m-darwin.so:
	@rpath/_rclpy.cpython-36m-darwin.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/Python (compatibility version 3.6.0, current version 3.6.0)
	@rpath/librcl.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_connext_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_generator_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_connext_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_introspection_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_opensplice_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_opensplice_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcl_interfaces__rosidl_typesupport_introspection_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librmw_implementation.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	@rpath/librmw.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librosidl_generator_c.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librcutils.dylib (compatibility version 0.0.0, current version 0.0.0)
```

So as to not split the conversation, this convo should be continued on ros2/ros2#437 where it was originally posted

**Pull request merged**
