### PR TITLE
install pytest and pytest-cov

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connect to ament/ament_tools#169.

The new dependencies need to be added to the install instructions in the wiki once this is merged.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Is the version from apt not acceptable ?

**Comment by dirk-thomas** [comment]
> Is the version from apt not acceptable ?

The Debian package of `pytest` and `pytest-cov` should be fine on Xenial. `pytest-runner` is not available as a Debian package in Xenial though. Our pipeline always installs the pip packages (mostly because of the non-Debian platforms) so I didn't bother adding those two packages also from Debian.

**Comment by mikaelarguedas** [comment]
> Our pipeline always installs the pip packages (mostly because of the non-Debian platforms) so I didn't bother adding those two packages also from Debian.

Agreed it doesnt change much for our CI given that they install from scratch every time.
I'm not sure but I though the motivation for relying on the apt versions wherever we can is to allow us and the users to have updates on this packages through their usual upgrade process and not having to update each of them by manually invoking pip.
Do you remember the motivation for installing all the other test dependencies from pip and apt ? (nose or mock for example?)

**Comment by dirk-thomas** [comment]
> Do you remember the motivation for installing all the other test dependencies from pip and apt ?

I guess we just didn't bother to skip some of the PIP installs on Ubuntu for packages which are installed from Debian packages.

**Comment by mikaelarguedas** [comment]
I'd suggest installing via `apt` whatever we recommend users to use via `apt`. This also allows the dependency part of the instructions to be aligned with the content of the Dockerfiles and the one of our machines.
I'm happy to provide a PR if you agree

**Comment by dirk-thomas** [comment]
> I'm happy to provide a PR if you agree

Sounds good to me. :+1:

**Pull request merged**
