### PR TITLE
Trigger RHEL jobs from the launcher as well.

### PR DESCRIPTION
**Pull request by clalancette**
Here's the diff from attempting to deploy this:

```
Updating job 'ci_launcher' (dry run)
    <<<
    --- remote config
    +++ new config
    @@ -215,0 +216 @@
    +predicted_jobs["linux-rhel"] = new Tuple("ci_linux-rhel", predict_build_number("ci_linux-rhel"))
    @@ -269,0 +271,13 @@
    +          </configs>
    +          <projects>ci_linux-rhel</projects>
    +          <condition>SUCCESS</condition>
    +          <triggerWithNoParameters>false</triggerWithNoParameters>
    +          <triggerFromChildProjects>false</triggerFromChildProjects>
    +        </hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
    +      </configs>
    +    </hudson.plugins.parameterizedtrigger.BuildTrigger>
    +    <hudson.plugins.parameterizedtrigger.BuildTrigger plugin="parameterized-trigger@2.35.2">
    +      <configs>
    +        <hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
    +          <configs>
    +            <hudson.plugins.parameterizedtrigger.CurrentBuildParameters />
    >>>
Updating job 'test_ci_launcher' (dry run)
    <<<
    --- remote config
    +++ new config
    @@ -215,0 +216 @@
    +predicted_jobs["linux-rhel"] = new Tuple("test_ci_linux-rhel", predict_build_number("test_ci_linux-rhel"))
    @@ -269,0 +271,13 @@
    +          </configs>
    +          <projects>test_ci_linux-rhel</projects>
    +          <condition>SUCCESS</condition>
    +          <triggerWithNoParameters>false</triggerWithNoParameters>
    +          <triggerFromChildProjects>false</triggerFromChildProjects>
    +        </hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
    +      </configs>
    +    </hudson.plugins.parameterizedtrigger.BuildTrigger>
    +    <hudson.plugins.parameterizedtrigger.BuildTrigger plugin="parameterized-trigger@2.35.2">
    +      <configs>
    +        <hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
    +          <configs>
    +            <hudson.plugins.parameterizedtrigger.CurrentBuildParameters />
    >>>
```

(I'm not totally sure why the new `parameterized-trigger` portion is there)

### CODE REVIEW

**Review by cottsay — APPROVED** [review]
:red_square: :tophat:

**Comment by clalancette** [comment]
I'm going to deploy this just to the `test_ci_launcher` job, and then run a test job there.

**Comment by clalancette** [comment]
I ran https://ci.ros2.org/view/All/job/test_ci_launcher/15/ and got the following output for the console:

* Linux [Build Status](http://ci.ros2.org/job/test_ci_linux/184/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/test_ci_linux-aarch64/70/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/test_ci_linux-rhel/40/)
* Windows [Build Status](http://ci.ros2.org/job/test_ci_windows/348/)

**Comment by clalancette** [comment]
And I've now deployed this.

**Pull request merged**
