### PR TITLE
Squash a few docker layers

### PR DESCRIPTION
**Pull request by sloretz**
Should get image below layer limit for building turtlebot demo on arm

(see https://github.com/ros2/ci/pull/100#issuecomment-329560974)

[Build Status](http://ci.ros2.org/job/ci_turtlebot-demo_linux-aarch64/100/)

### CODE REVIEW

**Comment by clalancette** [comment]
Agreed with @dirk-thomas .  Personally, I would just move/combine all of those comments above the RUN statement itself, which just makes it a bit easier to read.

**Comment by sloretz** [comment]
@dirk-thomas It's an abuse of command substitution, but it works. @clalancette comments moved above `RUN` in 48026bec703499640af12bced4141fdea63b09c1.

**Comment by dirk-thomas** [comment]
Yeah, very "creative" with the backticked comments :wink:

This looks much simpler now :+1:

**Comment by sloretz** [comment]
I'm going to squash/merge this. While the CI job isn't finished and it's not testing the last commit, I think the last commit changes are low risk and the build has gone far enough to show that enough layers have been squashed.

**Pull request merged**
