### PR TITLE
use Visual Studio 2019

### PR DESCRIPTION
**Pull request by dirk-thomas**
Prerequisites:

* [x] Visual Studio 2019 has been installed on all Windows nodes: https://github.com/ros2/build_cop/issues/168#issuecomment-481375908
* [x] `cmake` version 3.14 has been installed on all Windows nodes: https://github.com/ros2/build_cop/issues/168#issuecomment-481456015
* [x] `colcon-cmake` has been updated to support it: colcon/colcon-cmake#39.
* [x] A missing include has been added to `rcl`: ros2/rcl#413.
* New versions of the following custom packages are needed:
  * [x] `OpenCV` 3.4.6 for VS 2019 (& VS 2017) uploaded: https://github.com/ros2/ros2/releases/tag/opencv-archives

### CODE REVIEW

**Comment by dirk-thomas** [comment]
A [first build using VS 2019](https://ci.ros2.org/job/ci_windows_vs2019/11/) excluding packages needing OpenCV (`image_tools`, `intra_process_demo`) passed with only one compiler warning which has been ticketed [upstream in FastRTPS](https://github.com/eProsima/Fast-RTPS/issues/485).

**Comment by dirk-thomas** [comment]
Builds using the newly deployed [OpenCV 3.4.6](https://github.com/ros2/ros2/releases/tag/opencv-archives) pass - with VS 2019 as well as VS 2017.

**Comment by mjcarroll** [comment]
Based on this: https://doc.qt.io/qt-5/windows.html#supported-configurations Qt5 with VS2019 is not a "supported configuration" yet.  I can't find any evidence of a package built with 2019, either.

**Comment by dirk-thomas** [comment]
The build including the FastRTPS fix from eProsima/Fast-RTPS#489 addressing the compiler warning: [Build Status](https://ci.ros2.org/job/ci_windows_vs2019/19/)

**Comment by dirk-thomas** [comment]
OpenSplice will be updated once upstream provides an updated installer: ADLINK-IST/opensplice#86

**Comment by dirk-thomas** [comment]
> Based on this: https://doc.qt.io/qt-5/windows.html#supported-configurations Qt5 with VS2019 is not a "supported configuration" yet. I can't find any evidence of a package built with 2019, either.

I was able to run `rviz2` successfully with a VS2019 build using Qt 5.10 (the version currently being used on our Windows nodes).

**Comment by dirk-thomas** [comment]
Connext and OpenSplice build (using their existing VS2017 installers): [Build Status](https://ci.ros2.org/job/ci_windows_vs2019/20/)

**Comment by dirk-thomas** [comment]
It seems that everything is in place to put this back in review.

**Comment by dirk-thomas** [comment]
Follow up commit to pass the creation script: 7f3f8eef18988f720ac2f0692fcf61e38a3938e1.

**Pull request merged**
