### PR TITLE
Only run tests on rcutils for the TSA nightly

### PR DESCRIPTION
**Pull request by thomas-moulard**
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>

### CODE REVIEW

**Comment by thomas-moulard** [comment]
@nuclearsandwich As discussed offline - only keeping tests in rcutils as a "sanity check".

**Comment by thomas-moulard** [comment]
@emersonknapp PTAL

**Comment by nuclearsandwich** [comment]
I'll give some time for @emersonknapp to review and then merge.

**Comment by emersonknapp** [comment]
lgtm

**Pull request merged**
