### PR TITLE
Update cookbook version to install jsonschema on Windows.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Testing https://github.com/ros-infrastructure/ros2-cookbooks/pull/52

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Just testing the provisioning setup so it's only building ament_package

Windows [Build Status](https://ci.ros2.org/job/ci_windows/18823/)
Windows debug [Build Status](https://ci.ros2.org/job/ci_windows/18824/)

**Review by clalancette — COMMENTED** [review]
The sentiment looks good to me.  Refraining from approving until we merge in https://github.com/ros-infrastructure/ros2-cookbooks/pull/52 and update this accordingly.

**Comment by emersonknapp** [comment]
@nuclearsandwich all set here? Or are there more tests that need running?

**Comment by clalancette** [comment]
With the cookbook change now merged, I've updated this as well.  Here's another quick CI on all platforms just to check that things are being installed as we expect:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18186/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12721/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18847/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/18848/)

**Comment by clalancette** [comment]
OK, everything is green, and I confirmed that `jsonschema` got installed into all platforms.  So going ahead and merging.

**Pull request merged**
